// Generated by gencpp from file mavros_msgs/MountConfig.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_MOUNTCONFIG_H
#define MAVROS_MSGS_MESSAGE_MOUNTCONFIG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mavros_msgs
{
template <class ContainerAllocator>
struct MountConfig_
{
  typedef MountConfig_<ContainerAllocator> Type;

  MountConfig_()
    : header()
    , target_system(0)
    , target_component(0)
    , time_boot_ms(0)
    , flags(0)
    , quaternion()
    , angular_velocity_x(0.0)
    , angular_velocity_y(0.0)
    , angular_velocity_z(0.0)
    , failure_flags(0)  {
      quaternion.assign(0.0);
  }
  MountConfig_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , target_system(0)
    , target_component(0)
    , time_boot_ms(0)
    , flags(0)
    , quaternion()
    , angular_velocity_x(0.0)
    , angular_velocity_y(0.0)
    , angular_velocity_z(0.0)
    , failure_flags(0)  {
  (void)_alloc;
      quaternion.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _target_system_type;
  _target_system_type target_system;

   typedef uint8_t _target_component_type;
  _target_component_type target_component;

   typedef uint64_t _time_boot_ms_type;
  _time_boot_ms_type time_boot_ms;

   typedef uint8_t _flags_type;
  _flags_type flags;

   typedef boost::array<float, 4>  _quaternion_type;
  _quaternion_type quaternion;

   typedef float _angular_velocity_x_type;
  _angular_velocity_x_type angular_velocity_x;

   typedef float _angular_velocity_y_type;
  _angular_velocity_y_type angular_velocity_y;

   typedef float _angular_velocity_z_type;
  _angular_velocity_z_type angular_velocity_z;

   typedef uint64_t _failure_flags_type;
  _failure_flags_type failure_flags;





  typedef boost::shared_ptr< ::mavros_msgs::MountConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::MountConfig_<ContainerAllocator> const> ConstPtr;

}; // struct MountConfig_

typedef ::mavros_msgs::MountConfig_<std::allocator<void> > MountConfig;

typedef boost::shared_ptr< ::mavros_msgs::MountConfig > MountConfigPtr;
typedef boost::shared_ptr< ::mavros_msgs::MountConfig const> MountConfigConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::MountConfig_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::MountConfig_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::MountConfig_<ContainerAllocator1> & lhs, const ::mavros_msgs::MountConfig_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.target_system == rhs.target_system &&
    lhs.target_component == rhs.target_component &&
    lhs.time_boot_ms == rhs.time_boot_ms &&
    lhs.flags == rhs.flags &&
    lhs.quaternion == rhs.quaternion &&
    lhs.angular_velocity_x == rhs.angular_velocity_x &&
    lhs.angular_velocity_y == rhs.angular_velocity_y &&
    lhs.angular_velocity_z == rhs.angular_velocity_z &&
    lhs.failure_flags == rhs.failure_flags;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::MountConfig_<ContainerAllocator1> & lhs, const ::mavros_msgs::MountConfig_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::MountConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::MountConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::MountConfig_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::MountConfig_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::MountConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::MountConfig_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::MountConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f23c23b92915eeef7f5b09d790a38e5";
  }

  static const char* value(const ::mavros_msgs::MountConfig_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f23c23b92915eeeULL;
  static const uint64_t static_value2 = 0xf7f5b09d790a38e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::MountConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/MountConfig";
  }

  static const char* value(const ::mavros_msgs::MountConfig_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::MountConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# HilActuatorControls.msg\n"
"#\n"
"# ROS representation of MAVLink HIL_ACTUATOR_CONTROLS\n"
"# See mavlink message documentation here:\n"
"# https://mavlink.io/en/messages/common.html#GIMBAL_DEVICE_ATTITUDE_STATUS\n"
"std_msgs/Header header\n"
"uint8 target_system \n"
"uint8 target_component\n"
"uint64 time_boot_ms\n"
"uint8  flags\n"
"float32[4] quaternion\n"
"float32 angular_velocity_x\n"
"float32 angular_velocity_y\n"
"float32 angular_velocity_z\n"
"uint64 failure_flags\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mavros_msgs::MountConfig_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::MountConfig_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.target_system);
      stream.next(m.target_component);
      stream.next(m.time_boot_ms);
      stream.next(m.flags);
      stream.next(m.quaternion);
      stream.next(m.angular_velocity_x);
      stream.next(m.angular_velocity_y);
      stream.next(m.angular_velocity_z);
      stream.next(m.failure_flags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MountConfig_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::MountConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::MountConfig_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "target_system: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_system);
    s << indent << "target_component: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_component);
    s << indent << "time_boot_ms: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.time_boot_ms);
    s << indent << "flags: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flags);
    s << indent << "quaternion[]" << std::endl;
    for (size_t i = 0; i < v.quaternion.size(); ++i)
    {
      s << indent << "  quaternion[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.quaternion[i]);
    }
    s << indent << "angular_velocity_x: ";
    Printer<float>::stream(s, indent + "  ", v.angular_velocity_x);
    s << indent << "angular_velocity_y: ";
    Printer<float>::stream(s, indent + "  ", v.angular_velocity_y);
    s << indent << "angular_velocity_z: ";
    Printer<float>::stream(s, indent + "  ", v.angular_velocity_z);
    s << indent << "failure_flags: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.failure_flags);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_MOUNTCONFIG_H
